@startchen

entity Products {
  Name
  Description
  Price
}

entity InventoryTransactions {
  ProductID
  Change
  Reason
}

entity Customers {
  Name
  Email
}

entity Orders {
  OrderDate
  Total
  Status
  PaymentMethod
  ShippingAddress
}
entity OrderItems {
  Id
  OrderId
  ProductId
  Quantity
  UnitPrice
  TotalPrice
}
relationship Has { 
}
Orders -1- Has 
OrderItems -N- Has

relationship Refer {
}
OrderItems -N- Refer
Products -1- Refer

relationship Purchase {
}
Customers -1- Purchase
Orders -N- Purchase

relationship InventoryChange {
}

Products -1- InventoryChange
InventoryTransactions -N- InventoryChange
OrderItems -1- InventoryChange

@endchen