[project]
name = "part5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dask>=2025.5.1",
    "pymongo>=4.13.0",
    "requests>=2.32.3",
]
